Vagrant.configure(2) do |config|
  config.vm.box = "akasurde/fedora-24-x86_64"
  config.vm.provider :libvirt do |libvirt|
    libvirt.default_prefix = 'f24master'
    libvirt.storage_pool_name = "datadisk"
  end
  config.vm.define "Server6" do |foohost|
  end
end
